# app settings
app.version=0.1
app.username=${APP_USERNAMME\:time-control}
app.password=${APP_PASSWORD\:time-control}
app.logCliCommands=true
micronaut.application.name=time-control
micronaut.server.port=18000
# CORS Configuration
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.ui.allowed-origins[0]=http://localhost:4200
micronaut.server.cors.configurations.ui.allowed-methods[0]=GET
micronaut.server.cors.configurations.ui.allowed-methods[1]=POST
micronaut.server.cors.configurations.ui.allowed-methods[2]=PUT
micronaut.server.cors.configurations.ui.allowed-methods[3]=DELETE
micronaut.server.cors.configurations.ui.allowed-methods[4]=OPTIONS
micronaut.server.cors.configurations.ui.allowed-headers[0]=Authorization
micronaut.server.cors.configurations.ui.allowed-headers[1]=Content-Type
micronaut.server.cors.configurations.ui.allowed-headers[2]=Accept
micronaut.server.cors.configurations.ui.allow-credentials=true
# security
micronaut.security.endpoints.login.enabled=true
micronaut.security.endpoints.login.path=/login
micronaut.security.token.jwt.enabled=true
micronaut.security.authentication=bearer
micronaut.security.token.jwt.signatures.secret.generator.secret=${JWT_GENERATOR_SIGNATURE_SECRET\:pleaseChangeThisSecretForANewOne}
micronaut.security.enabled=true
micronaut.security.reject-not-found=true
# swagger
micronaut.security.intercept-url-map[0].pattern=/swagger/**
micronaut.security.intercept-url-map[0].access=isAnonymous()
micronaut.security.intercept-url-map[1].pattern=/swagger-ui/**
micronaut.security.intercept-url-map[1].access=isAnonymous()
micronaut.security.intercept-url-map[2].pattern=/login
micronaut.security.intercept-url-map[2].access=isAnonymous()
micronaut.router.static-resources.swagger-ui.mapping=/swagger-ui/**
micronaut.router.static-resources.swagger-ui.paths=classpath\:META-INF/swagger/views/swagger-ui
micronaut.router.static-resources.swagger.mapping=/swagger/**
micronaut.router.static-resources.swagger.paths=classpath\:META-INF/swagger
# logging
# micronaut.http.services.bitbucket.log-level=trace
# sqlite
datasources.default.db-type=sqlite
datasources.default.driver-class-name=org.sqlite.JDBC
datasources.default.url=jdbc:sqlite:database/time-control.db
# flyway
flyway.datasources.default.enabled=true
# data import
data-import.enabled=true
data-import.url=http://192.168.4.1/data
